name: diabetes_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.11
  - ipykernel=6.30.1
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.0.18
  - overrides=7.4.0
  - packaging=25.0
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pip=25.2
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - readline=8.3
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - altair==5.5.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - narwhals==2.10.1
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.3.1
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - pytz==2025.2
      - referencing==0.37.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - smmap==5.0.2
      - streamlit==1.51.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.2
      - tzdata==2025.2
      - watchdog==6.0.0
prefix: /home/sara/miniconda3/envs/diabetes_env
